<a href="https://colab.research.google.com/github/suhel64/FML/blob/main/diabetis%20logis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
     

In [4]:
dia=pd.read_csv('/content/diabetes.csv')

In [5]:
dia.head()

pregnancies  glucose  diastolic  triceps  insulin   bmi    dpf  age  \
0            6      148         72       35        0  33.6  0.627   50   
1            1       85         66       29        0  26.6  0.351   31   
2            8      183         64        0        0  23.3  0.672   32   
3            1       89         66       23       94  28.1  0.167   21   
4            0      137         40       35      168  43.1  2.288   33   

   diabetes  
0         1  
1         0  
2         1  
3         0  
4         1

In [24]:
dia.shape

(768, 9)

In [31]:
#Create feature and target array from such given data
X = dia.drop('diabetes', axis=1).values
y = dia['diabetes'].values

In [104]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=40)

In [105]:
from sklearn.preprocessing import StandardScaler    
st_x= StandardScaler()    
X_train= st_x.fit_transform(X_train)    
X_test= st_x.transform(X_test)

In [97]:
X_train.shape

(576, 8)

In [106]:
#3. Create model and train it
model = LogisticRegression(C=0.5)
model.fit(X_train,y_train)

LogisticRegression(C=0.5)

In [55]:
#attributes of your model
model.classes_

array([0, 1])

In [56]:
model.coef_

array([[ 0.06421753,  0.03409146, -0.01386986,  0.00341305, -0.00179319,
         0.10261022,  0.57149308,  0.03710828]])

In [57]:
model.predict_proba(X_train)

array([[0.99356241, 0.00643759],
       [0.54036345, 0.45963655],
       [0.68315005, 0.31684995],
       ...,
       [0.31583565, 0.68416435],
       [0.20317014, 0.79682986],
       [0.94356668, 0.05643332]])

In [107]:
model.score(X_train, y_train)

0.7801302931596091

In [85]:
y_pred = model.predict(X_train)
print(y_pred)

[0 1 0 1 0 0 1 0 1 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 1 0 0 1
 0 0 0 1 0 0 1 0 1 0 0 1 0 1 1 0 0 1 0 1 0 0 0 0 0 0 0 1 1 0 0 1 0 1 1 0 0
 0 1 1 0 0 0 0 1 0 1 0 0 0 1 1 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 1 1 0 0 0 0 0
 1 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 1 0 1 0 0
 1 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0 0 0 0
 0 1 1 0 0 1 1 1 0 0 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 1
 0 1 1 1 0 0 0 0 0 1 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 0 0 1 1 1 0 1 0 0 0 0 1
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1 0 0
 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 1 1 0 0 0 1 0 1 0 1 1 1 1 1 0 0 0 0 0 0
 0 0 1 0 0 1 0 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 0 0 0 1 0 1 0 0 1 0
 1 0 1 0 0 0 0 1 1 0 1 0 0 1 1 0 1 1 0 0 1 1 1 0 1 0 0 0 0 0 1 0 0 1 0 0 0
 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 1 1 0 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 1 1 0 1 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1 1 1
 0 0 0 0 0 0 0 0 1 0 1 0 

In [87]:
confusion_matrix(y_train, y_pred)

array([[337,  42],
       [ 77, 120]])